dist: trusty
sudo: required

addons:
  sonarcloud:
    organization: "cathive"

services:
- docker

before_install:
- docker pull koalaman/shellcheck

cache:
  directories:
  - '$HOME/.sonar/cache'

script:
 - docker run -v $(pwd)/assets:/assets koalaman/shellcheck --shell=bash /assets/check /assets/in /assets/out /assets/common.sh
- sonar-scanner

matrix:
  fast_finish: true