---
dist: trusty
sudo: required

language: bash

addons:
  sonarcloud:
    organization: "cathive"

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
  - docker run -v $(pwd)/assets:/assets -w="/assets" koalaman/shellcheck --shell=bash ./check ./in ./out ./common.sh
#  - sonar-scanner

matrix:
  fast_finish: true